import type { Category, Technique, TechniqueConnection } from '../types'

export const prefilledCategories: Category[] = [
  { id: 1, name: 'Guards', description: 'Positions on your back controlling the opponent' },
  { id: 2, name: 'Guard Passing', description: 'Techniques to bypass the opponent\'s guard' },
  { id: 3, name: 'Sweeps', description: 'Reversals from bottom position to top' },
  { id: 4, name: 'Submissions', description: 'Finishing techniques — chokes and joint locks' },
  { id: 5, name: 'Takedowns & Throws', description: 'Taking the fight to the ground' },
  { id: 6, name: 'Escapes', description: 'Recovering from bad positions' },
  { id: 7, name: 'Positions', description: 'Dominant control positions' },
]

export const prefilledTechniques: Technique[] = [
  // Guards (1xx)
  { id: 101, name: 'Closed Guard', categoryId: 1, difficulty: 'BEGINNER', isCustom: false,
    description: 'Classic guard with legs locked behind the opponent\'s back, controlling posture and creating attack angles.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bjj+closed+guard+fundamentals' },
  { id: 102, name: 'Half Guard', categoryId: 1, difficulty: 'BEGINNER', isCustom: false,
    description: 'One leg trapping one of the opponent\'s legs, providing guard retention and sweep opportunities.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bjj+half+guard+attacks+sweeps' },
  { id: 103, name: 'Butterfly Guard', categoryId: 1, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Seated guard using the hooks (insteps) against the opponent\'s thighs to off-balance and sweep.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bjj+butterfly+guard+complete+guide' },
  { id: 104, name: 'Spider Guard', categoryId: 1, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Gripping the opponent\'s sleeves while using feet on biceps to control distance and attack.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bjj+spider+guard+attacks+sweeps' },
  { id: 105, name: 'De La Riva Guard', categoryId: 1, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'One-leg hook on the outside of the opponent\'s leg with sleeve/ankle control.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=de+la+riva+guard+bjj+basics' },
  { id: 106, name: 'X-Guard', categoryId: 1, difficulty: 'ADVANCED', isCustom: false,
    description: 'Both hooks under opponent\'s thighs in an X shape, creating extreme off-balance for sweeps.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=x+guard+bjj+sweeps+entries' },
  { id: 107, name: 'Lasso Guard', categoryId: 1, difficulty: 'ADVANCED', isCustom: false,
    description: 'Wrapping the arm in a lasso with the leg to immobilize the arm and create attack angles.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=lasso+guard+bjj+sweeps+submissions' },
  { id: 108, name: 'Rubber Guard', categoryId: 1, difficulty: 'ADVANCED', isCustom: false,
    description: 'High guard position with leg behind the neck, popularised by Eddie Bravo.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=rubber+guard+bjj+10th+planet' },
  { id: 109, name: 'Single Leg X (SLX)', categoryId: 1, difficulty: 'ADVANCED', isCustom: false,
    description: 'One hook between the opponent\'s legs controlling a single leg for sweeps and leg-lock entries.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=single+leg+x+guard+bjj+ashi+garami' },
  { id: 110, name: 'Worm Guard', categoryId: 1, difficulty: 'ELITE', isCustom: false,
    description: 'DLR variation using the lapel threaded around the leg for extreme control and sweeps.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=worm+guard+bjj+keenan+cornelius' },

  // Guard Passing (2xx)
  { id: 201, name: 'Torreando Pass', categoryId: 2, difficulty: 'BEGINNER', isCustom: false,
    description: 'Using grips on the knees/ankles to swing the legs aside and pass laterally.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=torreando+pass+bjj+fundamentals' },
  { id: 202, name: 'Double Under Pass', categoryId: 2, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Shooting both arms under the legs to stack and pass the guard.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=double+under+pass+bjj+pressure+passing' },
  { id: 203, name: 'Over-Under Pass', categoryId: 2, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'One arm over one leg and one arm under the other, a powerful pressure pass.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=over+under+pass+bjj+bernardo+faria' },
  { id: 204, name: 'Leg Drag', categoryId: 2, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Dragging one leg across the body while maintaining hip connection to create an angle for passing.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=leg+drag+pass+bjj+technique' },
  { id: 205, name: 'Knee Slice Pass', categoryId: 2, difficulty: 'BEGINNER', isCustom: false,
    description: 'Driving the knee through the guard while controlling the hip.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=knee+slice+pass+bjj+fundamentals' },
  { id: 206, name: 'Smash Pass', categoryId: 2, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Stacking the opponent\'s legs while driving forward to flatten and pass.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=smash+pass+bjj+no+gi+technique' },
  { id: 207, name: 'Bullfighter Pass', categoryId: 2, difficulty: 'BEGINNER', isCustom: false,
    description: 'Gripping both ankles/knees and redirecting the legs to either side.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bullfighter+pass+bjj+ankle+grip' },
  { id: 208, name: 'HQ / Headquarters', categoryId: 2, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Neutral passing position inside the guard, used to control and set up leg locks or passes.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=headquarters+position+bjj+nogi+passing' },

  // Sweeps (3xx)
  { id: 301, name: 'Hip Bump Sweep', categoryId: 3, difficulty: 'BEGINNER', isCustom: false,
    description: 'Posting the hand and bumping the hip forward from closed guard to take top position.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=hip+bump+sweep+bjj+closed+guard' },
  { id: 302, name: 'Scissor Sweep', categoryId: 3, difficulty: 'BEGINNER', isCustom: false,
    description: 'Using a scissoring motion of the legs from closed guard to knock the opponent over.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=scissor+sweep+bjj+closed+guard+technique' },
  { id: 303, name: 'Flower Sweep (Pendulum)', categoryId: 3, difficulty: 'BEGINNER', isCustom: false,
    description: 'From closed guard, hooking a leg and sweeping with a pendulum motion.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=flower+sweep+pendulum+bjj+closed+guard' },
  { id: 304, name: 'Butterfly Sweep', categoryId: 3, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Using butterfly hooks to off-balance the opponent and sweep to the side.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=butterfly+sweep+bjj+technique+marcelo' },
  { id: 305, name: 'X-Guard Sweep', categoryId: 3, difficulty: 'ADVANCED', isCustom: false,
    description: 'Sweeping from X-guard by extending the legs to dump the opponent forward or backward.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=x+guard+sweep+bjj+standing' },
  { id: 306, name: 'Berimbolo', categoryId: 3, difficulty: 'ELITE', isCustom: false,
    description: 'A spinning inversion from De La Riva to take the back or gain dominant position.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=berimbolo+bjj+mendes+brothers+technique' },
  { id: 307, name: 'De La Riva Sweep', categoryId: 3, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Various sweeps from the De La Riva guard attacking the near or far leg.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=de+la+riva+sweep+bjj+basic+intermediate' },
  { id: 308, name: 'Tripod Sweep', categoryId: 3, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Using foot on the hip and foot on the bicep to sweep the opponent.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=tripod+sweep+bjj+spider+guard+no+gi' },

  // Submissions (4xx)
  { id: 401, name: 'Armbar', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Hyperextending the elbow joint by controlling the arm across the body — applied from many positions.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=armbar+bjj+guard+mount+technique+setup' },
  { id: 402, name: 'Triangle Choke', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Locking the head and arm with the legs in a figure-4 to cut off blood flow to the brain.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=triangle+choke+bjj+guard+technique' },
  { id: 403, name: 'Kimura', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'A figure-4 grip on the wrist rotating the shoulder joint — applied from many positions.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=kimura+bjj+closed+guard+side+control' },
  { id: 404, name: 'Omoplata', categoryId: 4, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Shoulder lock using the legs to control the arm and rotate the shoulder.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=omoplata+bjj+submission+guard' },
  { id: 405, name: 'Rear Naked Choke', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Blood choke from the back — arm under the chin, arm behind the head.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=rear+naked+choke+bjj+finishing+technique' },
  { id: 406, name: 'Guillotine Choke', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Arm around the neck cutting off blood flow, applied from standing or guard.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=guillotine+choke+bjj+high+elbow+arm+in' },
  { id: 407, name: 'Outside Heel Hook', categoryId: 4, difficulty: 'ADVANCED', isCustom: false,
    description: 'Rotating the heel outward to attack the lateral structures of the knee.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=outside+heel+hook+bjj+nogi+leg+lock' },
  { id: 408, name: 'Inside Heel Hook', categoryId: 4, difficulty: 'ELITE', isCustom: false,
    description: 'Rotating the heel inward to attack the medial structures of the knee — highly dangerous.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=inside+heel+hook+bjj+mechanics+defense' },
  { id: 409, name: 'Straight Ankle Lock', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Applying pressure against the Achilles tendon to attack the ankle.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=straight+ankle+lock+bjj+fundamentals' },
  { id: 410, name: 'Kneebar', categoryId: 4, difficulty: 'ADVANCED', isCustom: false,
    description: 'Hyperextending the knee joint, similar to an armbar but on the leg.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=kneebar+bjj+submission+entry+technique' },
  { id: 411, name: 'Darce Choke', categoryId: 4, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Arm-in choke using a figure-4 through the neck, applied from turtle or guard.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=darce+choke+bjj+nogi+setup+finish' },
  { id: 412, name: 'Anaconda Choke', categoryId: 4, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Similar to the Darce but with a different arm position, often from front headlock.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=anaconda+choke+bjj+front+headlock+nogi' },
  { id: 413, name: 'Bow and Arrow Choke', categoryId: 4, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Powerful collar choke from the back using the belt/pants grip for finishing leverage.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=bow+and+arrow+choke+bjj+gi+back+control' },
  { id: 414, name: 'Cross Collar Choke', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Double collar grip from mount or guard crossing over to choke.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=cross+collar+choke+bjj+mount+guard+gi' },
  { id: 415, name: 'Ezekiel Choke', categoryId: 4, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Sleeve-grip choke from mount, can even be applied inside the opponent\'s guard.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=ezekiel+choke+bjj+mount+technique' },
  { id: 416, name: 'Americana (Keylock)', categoryId: 4, difficulty: 'BEGINNER', isCustom: false,
    description: 'Figure-4 shoulder lock bending the wrist upward — applied from mount or side control.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=americana+keylock+bjj+mount+side+control' },

  // Takedowns & Throws (5xx)
  { id: 501, name: 'Double Leg Takedown', categoryId: 5, difficulty: 'BEGINNER', isCustom: false,
    description: 'Shooting in on both legs and driving to lift/trip the opponent to the ground.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=double+leg+takedown+wrestling+bjj' },
  { id: 502, name: 'Single Leg Takedown', categoryId: 5, difficulty: 'BEGINNER', isCustom: false,
    description: 'Controlling one leg and using trips or lifts to bring the opponent down.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=single+leg+takedown+bjj+wrestling+finish' },
  { id: 503, name: 'Hip Throw (O-goshi)', categoryId: 5, difficulty: 'BEGINNER', isCustom: false,
    description: 'Loading the opponent onto the hip and rotating to throw them to the ground.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=o+goshi+hip+throw+judo+bjj' },
  { id: 504, name: 'Seoi Nage', categoryId: 5, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Pulling the opponent over the shoulder for a large throw.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=seoi+nage+shoulder+throw+judo+bjj' },
  { id: 505, name: 'Uchi Mata', categoryId: 5, difficulty: 'ADVANCED', isCustom: false,
    description: 'Sweeping inside the opponent\'s leg while breaking their balance.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=uchi+mata+judo+bjj+inner+thigh+throw' },
  { id: 506, name: 'Osoto Gari', categoryId: 5, difficulty: 'BEGINNER', isCustom: false,
    description: 'Reaping the opponent\'s leg from the outside while pushing them backward.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=osoto+gari+judo+bjj+outer+reap' },
  { id: 507, name: 'Ankle Pick', categoryId: 5, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Grabbing the ankle while pushing the head to trip the opponent.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=ankle+pick+bjj+wrestling+takedown' },
  { id: 508, name: "Fireman's Carry", categoryId: 5, difficulty: 'ADVANCED', isCustom: false,
    description: 'Loading the opponent across the back by gripping arm and ankle.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=fireman+carry+wrestling+bjj+takedown' },

  // Escapes (6xx)
  { id: 601, name: 'Bridge and Roll (Upa)', categoryId: 6, difficulty: 'BEGINNER', isCustom: false,
    description: 'Explosive bridge from mount to roll the opponent, recovering guard or taking top.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=upa+bridge+roll+escape+mount+bjj' },
  { id: 602, name: 'Elbow-Knee Escape', categoryId: 6, difficulty: 'BEGINNER', isCustom: false,
    description: 'Creating space by shrimping the hips out and replacing guard from underneath.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=elbow+knee+escape+shrimp+bjj+mount' },
  { id: 603, name: 'Side Control Escape', categoryId: 6, difficulty: 'BEGINNER', isCustom: false,
    description: 'Using the shrimp movement to recover guard from side control.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=side+control+escape+bjj+shrimp+recover+guard' },
  { id: 604, name: 'Back Escape', categoryId: 6, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Protecting the neck, working the seat belt off, and recovering guard from back control.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=back+escape+bjj+seat+belt+recover+guard' },
  { id: 605, name: 'Guillotine Defense', categoryId: 6, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Posturing up, turning into the choke, and finding the neck to escape.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=guillotine+choke+defense+escape+bjj' },
  { id: 606, name: 'Triangle Defense', categoryId: 6, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Stacking, posturing, and using grip breaks to escape the triangle choke.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=triangle+choke+defense+escape+bjj' },

  // Positions (7xx)
  { id: 701, name: 'Mount', categoryId: 7, difficulty: 'BEGINNER', isCustom: false,
    description: 'Sitting on top of the opponent\'s torso — one of the most dominant positions in BJJ.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=mount+position+bjj+attacks+control' },
  { id: 702, name: 'Side Control', categoryId: 7, difficulty: 'BEGINNER', isCustom: false,
    description: 'Controlling the opponent from the side with chest-to-chest pressure.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=side+control+bjj+submissions+transitions' },
  { id: 703, name: 'Back Control', categoryId: 7, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Attaching to the opponent\'s back with hooks in, the most dangerous position in BJJ.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=back+control+bjj+seat+belt+hooks+finishing' },
  { id: 704, name: 'North-South', categoryId: 7, difficulty: 'INTERMEDIATE', isCustom: false,
    description: 'Controlling the opponent head-to-head, perpendicular to their body.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=north+south+position+bjj+control+submissions' },
  { id: 705, name: 'Knee on Belly', categoryId: 7, difficulty: 'BEGINNER', isCustom: false,
    description: 'Driving the knee into the opponent\'s belly — a transitional and attacking position.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=knee+on+belly+bjj+attacks+pressure' },
  { id: 706, name: 'Turtle Position', categoryId: 7, difficulty: 'BEGINNER', isCustom: false,
    description: 'Defensive position on all fours — the opponent must break it open to attack.',
    youtubeUrl: 'https://www.youtube.com/results?search_query=turtle+position+bjj+attacks+defense' },
]

export const prefilledConnections: TechniqueConnection[] = [
  // Closed Guard attacks
  { fromTechniqueId: 101, toTechniqueId: 401, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 404, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 406, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 301, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 302, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 101, toTechniqueId: 303, connectionType: 'FOLLOW_UP' },
  // Submission combinations
  { fromTechniqueId: 402, toTechniqueId: 401, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 402, toTechniqueId: 404, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 401, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 401, toTechniqueId: 404, connectionType: 'TRANSITION' },
  { fromTechniqueId: 403, toTechniqueId: 406, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 403, toTechniqueId: 401, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 301, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  // Half Guard
  { fromTechniqueId: 102, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 102, toTechniqueId: 406, connectionType: 'FOLLOW_UP' },
  // Butterfly Guard
  { fromTechniqueId: 103, toTechniqueId: 304, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 103, toTechniqueId: 411, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 103, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  // De La Riva
  { fromTechniqueId: 105, toTechniqueId: 306, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 105, toTechniqueId: 307, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 105, toTechniqueId: 703, connectionType: 'TRANSITION' },
  // X-Guard
  { fromTechniqueId: 106, toTechniqueId: 305, connectionType: 'FOLLOW_UP' },
  // SLX → leg locks
  { fromTechniqueId: 109, toTechniqueId: 409, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 109, toTechniqueId: 407, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 109, toTechniqueId: 408, connectionType: 'FOLLOW_UP' },
  // Spider Guard
  { fromTechniqueId: 104, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 104, toTechniqueId: 308, connectionType: 'FOLLOW_UP' },
  // Lasso Guard
  { fromTechniqueId: 107, toTechniqueId: 404, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 107, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  // From Mount
  { fromTechniqueId: 701, toTechniqueId: 401, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 701, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 701, toTechniqueId: 414, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 701, toTechniqueId: 415, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 701, toTechniqueId: 416, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 701, toTechniqueId: 601, connectionType: 'COUNTER' },
  { fromTechniqueId: 701, toTechniqueId: 602, connectionType: 'COUNTER' },
  // From Side Control
  { fromTechniqueId: 702, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 702, toTechniqueId: 416, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 702, toTechniqueId: 704, connectionType: 'TRANSITION' },
  { fromTechniqueId: 702, toTechniqueId: 705, connectionType: 'TRANSITION' },
  { fromTechniqueId: 702, toTechniqueId: 701, connectionType: 'TRANSITION' },
  { fromTechniqueId: 702, toTechniqueId: 603, connectionType: 'COUNTER' },
  // From Back Control
  { fromTechniqueId: 703, toTechniqueId: 405, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 703, toTechniqueId: 413, connectionType: 'FOLLOW_UP' },
  // North-South
  { fromTechniqueId: 704, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 704, toTechniqueId: 412, connectionType: 'FOLLOW_UP' },
  // Knee on Belly
  { fromTechniqueId: 705, toTechniqueId: 401, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 705, toTechniqueId: 402, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 705, toTechniqueId: 403, connectionType: 'FOLLOW_UP' },
  // Takedowns → positions
  { fromTechniqueId: 501, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 502, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 503, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 504, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 506, toTechniqueId: 702, connectionType: 'TRANSITION' },
  // Guard passes → positions
  { fromTechniqueId: 201, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 202, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 203, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 204, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 205, toTechniqueId: 702, connectionType: 'TRANSITION' },
  { fromTechniqueId: 208, toTechniqueId: 407, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 208, toTechniqueId: 409, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 208, toTechniqueId: 408, connectionType: 'FOLLOW_UP' },
  // Turtle
  { fromTechniqueId: 706, toTechniqueId: 411, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 706, toTechniqueId: 412, connectionType: 'FOLLOW_UP' },
  { fromTechniqueId: 706, toTechniqueId: 703, connectionType: 'TRANSITION' },
  // Escapes back to guard
  { fromTechniqueId: 601, toTechniqueId: 101, connectionType: 'TRANSITION' },
  { fromTechniqueId: 602, toTechniqueId: 101, connectionType: 'TRANSITION' },
  { fromTechniqueId: 604, toTechniqueId: 101, connectionType: 'TRANSITION' },
  // Berimbolo → back
  { fromTechniqueId: 306, toTechniqueId: 703, connectionType: 'TRANSITION' },
]
